# Agenda
- Lamda function - Samuel
- Data process - Teresa

In [1]:
def add_two_numbers(x, y):
    result = x + y
    return result

In [3]:
add_two_numbers(3, 5)

8

In [ ]:
lambda x, y: x + y

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame(
    {
        "a": [12, 13, 5, 4, 2],
        "b": [2, 5, 9, 0, 3]
    }
)

In [6]:
df

    a  b
0  12  2
1  13  5
2   5  9
3   4  0
4   2  3

In [13]:
df.apply(lambda x: x["a"] + x["b"], axis=1)

0    14
1    18
2    14
3     4
4     5
dtype: int64

In [14]:
df["c"] = df.apply(lambda x: x["a"] + x["b"], axis=1)

In [15]:
df

    a  b   c
0  12  2  14
1  13  5  18
2   5  9  14
3   4  0   4
4   2  3   5

In [11]:
df["a"].apply(lambda x: x + 2)

0    14
1    15
2     7
3     6
4     4
Name: a, dtype: int64

In [12]:
df['a']

0    12
1    13
2     5
3     4
4     2
Name: a, dtype: int64

In [16]:
file = pd.ExcelFile("crimeinenglandandwalesappendixtablesyejun2025final.xlsx")

In [17]:
file.sheet_names

['Cover Sheet',
 'Table of contents',
 'Notes_A1 to A4',
 'Table_A1a',
 'Table_A1b',
 'Table_A2a',
 'Table_A2b',
 'Table_A3a',
 'Table_A3b',
 'Table_A4a',
 'Table_A4b',
 'Notes_A5 to A7',
 'Table_A5a',
 'Table_A5b',
 'Summary Table_A6',
 'Table_A7',
 'Notes_B1 to B10',
 'Worksheet_B1',
 'Table_B2',
 'Table_B3',
 'Table_B4',
 'Worksheet_B5',
 'Worksheet_B6',
 'Worksheet_B7',
 'Table_B8',
 'Worksheet_B9',
 'Table_B10',
 'Notes_C1 to C5',
 'Table_C1',
 'Table_C2',
 'Table_C3',
 'Table_C4',
 'Table_C5',
 'Notes_D1 to D6',
 'Worksheet_D1',
 'Worksheet_D2',
 'Table_D3',
 'Table_D4',
 'Table_D5',
 'Worksheet_D6',
 'Notes_E1 to E3',
 'Table_E1',
 'Worksheet_E2',
 'Table_E3']

In [21]:
sheet1 = pd.read_excel(file, sheet_name='Table_A1a', skiprows=7)

In [22]:
sheet1

,Offence group\n[note 5],Jan 1981 to Dec 1981,Jan 1983 to Dec 1983,Jan 1987 to Dec 1987,Jan 1991 to Dec 1991,Jan 1993 to Dec 1993,Jan 1995 to Dec 1995,Jan 1997 to Dec 1997,Jan 1999 to Dec 1999,Apr 2001 to Mar 2002,...,Apr 2015 to Mar 2016,Apr 2016 to Mar 2017,Apr 2017 to Mar 2018,Apr 2018 to Mar 2019,Apr 2019 to Mar 2020\n[note 7],Apr 2022 to Mar 2023,Apr 2023 to Mar 2024,Apr 2024 to Mar 2025,Jul 2023 to Jun 2024,Jul 2024 to Jun 2025
0,VIOLENCE,2063,2014,2265,2900,3768,4464,3746,3375,2551,...,1468,1432,1426,1344,1239,998,1125,1103,1125,1134
1,Violence with injury,1226,1208,1592,1778,2407,2622,2365,1974,1507,...,631,702,666,714,591,423,533,391,562,392
2,Wounding,544,454,613,791,874,1077,940,728,709,...,331,379,242,332,341,158,253,136,248,155
3,Assault with minor injury,682,806,978,987,1533,1545,1425,1245,798,...,300,323,423,382,250,265,279,255,315,237
4,Violence without injury,838,806,674,1122,1360,1843,1381,1401,1043,...,837,730,760,630,648,575,592,711,563,742
5,ROBBERY,164,145,178,195,254,322,338,394,340,...,153,129,160,192,127,72,113,83,139,65
6,THEFT OFFENCES [note 8],6292,7136,8227,9792,11512,11615,10023,8584,7209,...,3698,3327,3578,3750,3299,2650,2686,2801,2791,2752
7,Theft from the person,434,505,329,451,611,680,613,593,588,...,363,370,425,447,367,247,347,467,363,462
8,Snatch theft from person,86,63,50,85,84,72,81,56,67,...,43,41,60,58,33,31,78,92,78,93
9,Stealth theft from person,258,315,168,264,345,365,358,322,334,...,197,194,175,209,191,112,126,153,133,151
10,Attempted snatch or stealth theft from...,90,127,111,102,182,242,174,215,188,...,123,136,190,180,143,105,143,222,152,218
11,Other theft of personal property,1586,1729,1798,1737,1933,2073,1942,1565,1370,...,764,640,655,739,612,425,446,432,459,423
12,Unweighted base - number of people aged 16 and...,9898,11017,10391,10059,14510,16337,14937,19398,32787,...,35324,35420,34715,34163,33734,31183,30847,31532,31799,31791
13,Domestic burglary,975,1129,1461,1723,2430,2342,2110,1851,1423,...,697,650,691,699,582,409,402,398,409,376
14,With entry,694,723,869,1166,1592,1510,1273,1236,924,...,425,428,432,441,352,211,222,222,224,218
15,With loss,584,623,714,982,1342,1178,1030,964,673,...,297,275,296,301,240,136,127,132,125,131
16,No loss,110,100,155,184,250,332,243,272,251,...,128,153,136,140,113,75,95,90,99,88
17,Attempts,281,405,591,556,838,831,837,615,499,...,272,222,259,258,229,198,180,177,185,158
18,Domestic burglary in a dwelling,752,916,1225,1372,1751,1708,1547,1230,958,...,492,464,506,517,450,303,294,285,291,270
19,With entry,475,532,666,866,1015,973,818,730,539,...,263,276,295,298,241,141,150,132,143,136
20,With loss,374,454,519,714,818,763,627,521,385,...,167,164,188,192,156,88,74,86,76,78
21,No loss,101,79,147,151,197,210,191,209,154,...,96,112,107,106,85,53,76,46,67,59
22,Attempts,277,384,559,506,736,735,730,500,419,...,229,187,212,219,209,162,144,153,148,133
23,Domestic burglary in a non-connected build...,223,213,236,351,679,633,562,621,465,...,206,186,185,182,132,106,108,113,118,106
24,With entry,219,191,203,301,577,537,455,506,385,...,162,152,137,143,111,70,72,90,81,82
25,With loss,210,170,196,268,524,415,404,442,288,...,130,111,108,109,84,47,53,46,50,53
26,No loss,9,21,8,33,53,122,52,63,97,...,32,41,29,34,27,22,19,44,31,29
27,Attempts,4,21,32,50,102,96,107,115,80,...,43,35,47,39,21,37,36,23,36,24
28,Other household theft,1323,1366,1297,1457,1622,1559,1380,1240,981,...,671,588,593,651,581,613,556,656,606,657
29,Theft from a dwelling,154,152,129,96,195,220,174,160,125,...,68,70,68,66,72,53,39,34,44,28
30,Theft from outside a dwelling,1169,1214,1168,1361,1428,1339,1206,1080,857,...,603,518,525,584,509,560,517,622,562,629
31,Vehicle-related theft,1757,2118,2953,3823,4337,4304,3452,2939,2487,...,877,787,918,900,886,726,732,666,747,649
32,Theft from vehicles,1290,1540,2125,2424,2561,2524,2135,1801,1495,...,643,573,652,648,634,499,465,437,478,424
33,Theft of vehicles,286,284,398,516,550,497,372,327,314,...,79,58,82,81,80,98,93,102,100,96
34,Attempts of and from vehicles,180,294,431,883,1227,1283,945,811,679,...,155,156,185,171,173,128,174,127,169,129
35,Bicycle theft,217,288,389,601,578,657,526,395,359,...,326,292,295,315,271,230,203,183,207,185
36,CRIMINAL DAMAGE,2784,2833,2976,2676,3301,3386,3060,2895,2672,...,1210,1169,1083,1145,997,664,664,608,668,587
37,Criminal damage to a vehicle,1592,1720,1638,1669,1781,1847,1667,1601,1511,...,832,797,693,814,675,439,402,373,422,367
38,Arson and other criminal damage,1192,1114,1337,1008,1520,1538,1393,1294,1161,...,378,372,390,331,323,225,263,235,245,220
39,Unweighted base - number of households,9916,11030,10392,10043,14491,16310,14900,19357,32782,...,35248,35334,34636,34103,33655,30822,30704,31375,31647,31631
40,ALL CSEW HEADLINE CRIME EXCLUDING FRAUD AND CO...,11303,12128,13647,15564,18835,19786,17168,15247,12771,...,6529,6057,6247,6431,5661,4385,4589,4595,4722,4538
41,Unweighted base - number of people aged 16 and...,9898,11017,10391,10059,14510,16337,14937,19398,32787,...,35324,35420,34715,34163,33734,31183,30847,31532,31799,31791
42,Fraud [note 9][note 10],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],3395,3255,3809,3676,3526,3177,4159,3560,4072
43,Bank and credit account fraud,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],2485,2241,2579,2474,2135,1885,2449,2092,2495
44,Consumer and retail fraud [note 11],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],736,873,1019,914,825,883,1091,963,1074
45,Advance fee fraud,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],77,69,57,60,391,302,381,333,298
46,Other fraud [note 12],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],97,71,154,227,175,106,237,173,205
47,Computer misuse [note 9][note 10],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],1764,1227,966,876,745,1022,692,952,663
48,Computer virus,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],1191,712,444,360,123,139,128,131,127
49,Unauthorised access to personal inform...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],573,516,522,516,622,883,564,821,536
50,Unweighted base - number of people aged 16 and...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],17171,25725,34163,33734,31183,30847,31532,31799,31791
51,ALL CSEW HEADLINE CRIME INCLUDING FRAUD AND CO...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],11216,10729,11207,10213,8656,8787,9445,9235,9273
52,Unweighted base - number of people aged 16 and...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],35420,34715,34163,33734,31183,30847,31532,31799,31791

In [24]:
mapping = {"VIOLENCE": ["Violence with injury", 
                                 "Wounding", "Assault with minor injury", 
                                 "Violence without injury"]}

In [25]:
sheet1.columns

Index(['Offence group\n[note 5]', 'Jan 1981 to Dec 1981',
       'Jan 1983 to Dec 1983', 'Jan 1987 to Dec 1987', 'Jan 1991 to Dec 1991',
       'Jan 1993 to Dec 1993', 'Jan 1995 to Dec 1995', 'Jan 1997 to Dec 1997',
       'Jan 1999 to Dec 1999', 'Apr 2001 to Mar 2002', 'Apr 2002 to Mar 2003',
       'Apr 2003 to Mar 2004', 'Apr 2004 to Mar 2005', 'Apr 2005 to Mar 2006',
       'Apr 2006 to Mar 2007', 'Apr 2007 to Mar 2008', 'Apr 2008 to Mar 2009',
       'Apr 2009 to Mar 2010', 'Apr 2010 to Mar 2011', 'Apr 2011 to Mar 2012',
       'Apr 2012 to Mar 2013\n[note 6]', 'Apr 2013 to Mar 2014',
       'Apr 2014 to Mar 2015', 'Apr 2015 to Mar 2016', 'Apr 2016 to Mar 2017',
       'Apr 2017 to Mar 2018', 'Apr 2018 to Mar 2019',
       'Apr 2019 to Mar 2020\n[note 7]', 'Apr 2022 to Mar 2023',
       'Apr 2023 to Mar 2024', 'Apr 2024 to Mar 2025', 'Jul 2023 to Jun 2024',
       'Jul 2024 to Jun 2025'],
      dtype='object')

In [27]:
sheet1.rename(columns={"Offence group\n[note 5]": "offence_group"}, inplace=True)

In [28]:
sheet1

,offence_group,Jan 1981 to Dec 1981,Jan 1983 to Dec 1983,Jan 1987 to Dec 1987,Jan 1991 to Dec 1991,Jan 1993 to Dec 1993,Jan 1995 to Dec 1995,Jan 1997 to Dec 1997,Jan 1999 to Dec 1999,Apr 2001 to Mar 2002,...,Apr 2015 to Mar 2016,Apr 2016 to Mar 2017,Apr 2017 to Mar 2018,Apr 2018 to Mar 2019,Apr 2019 to Mar 2020\n[note 7],Apr 2022 to Mar 2023,Apr 2023 to Mar 2024,Apr 2024 to Mar 2025,Jul 2023 to Jun 2024,Jul 2024 to Jun 2025
0,VIOLENCE,2063,2014,2265,2900,3768,4464,3746,3375,2551,...,1468,1432,1426,1344,1239,998,1125,1103,1125,1134
1,Violence with injury,1226,1208,1592,1778,2407,2622,2365,1974,1507,...,631,702,666,714,591,423,533,391,562,392
2,Wounding,544,454,613,791,874,1077,940,728,709,...,331,379,242,332,341,158,253,136,248,155
3,Assault with minor injury,682,806,978,987,1533,1545,1425,1245,798,...,300,323,423,382,250,265,279,255,315,237
4,Violence without injury,838,806,674,1122,1360,1843,1381,1401,1043,...,837,730,760,630,648,575,592,711,563,742
5,ROBBERY,164,145,178,195,254,322,338,394,340,...,153,129,160,192,127,72,113,83,139,65
6,THEFT OFFENCES [note 8],6292,7136,8227,9792,11512,11615,10023,8584,7209,...,3698,3327,3578,3750,3299,2650,2686,2801,2791,2752
7,Theft from the person,434,505,329,451,611,680,613,593,588,...,363,370,425,447,367,247,347,467,363,462
8,Snatch theft from person,86,63,50,85,84,72,81,56,67,...,43,41,60,58,33,31,78,92,78,93
9,Stealth theft from person,258,315,168,264,345,365,358,322,334,...,197,194,175,209,191,112,126,153,133,151
10,Attempted snatch or stealth theft from...,90,127,111,102,182,242,174,215,188,...,123,136,190,180,143,105,143,222,152,218
11,Other theft of personal property,1586,1729,1798,1737,1933,2073,1942,1565,1370,...,764,640,655,739,612,425,446,432,459,423
12,Unweighted base - number of people aged 16 and...,9898,11017,10391,10059,14510,16337,14937,19398,32787,...,35324,35420,34715,34163,33734,31183,30847,31532,31799,31791
13,Domestic burglary,975,1129,1461,1723,2430,2342,2110,1851,1423,...,697,650,691,699,582,409,402,398,409,376
14,With entry,694,723,869,1166,1592,1510,1273,1236,924,...,425,428,432,441,352,211,222,222,224,218
15,With loss,584,623,714,982,1342,1178,1030,964,673,...,297,275,296,301,240,136,127,132,125,131
16,No loss,110,100,155,184,250,332,243,272,251,...,128,153,136,140,113,75,95,90,99,88
17,Attempts,281,405,591,556,838,831,837,615,499,...,272,222,259,258,229,198,180,177,185,158
18,Domestic burglary in a dwelling,752,916,1225,1372,1751,1708,1547,1230,958,...,492,464,506,517,450,303,294,285,291,270
19,With entry,475,532,666,866,1015,973,818,730,539,...,263,276,295,298,241,141,150,132,143,136
20,With loss,374,454,519,714,818,763,627,521,385,...,167,164,188,192,156,88,74,86,76,78
21,No loss,101,79,147,151,197,210,191,209,154,...,96,112,107,106,85,53,76,46,67,59
22,Attempts,277,384,559,506,736,735,730,500,419,...,229,187,212,219,209,162,144,153,148,133
23,Domestic burglary in a non-connected build...,223,213,236,351,679,633,562,621,465,...,206,186,185,182,132,106,108,113,118,106
24,With entry,219,191,203,301,577,537,455,506,385,...,162,152,137,143,111,70,72,90,81,82
25,With loss,210,170,196,268,524,415,404,442,288,...,130,111,108,109,84,47,53,46,50,53
26,No loss,9,21,8,33,53,122,52,63,97,...,32,41,29,34,27,22,19,44,31,29
27,Attempts,4,21,32,50,102,96,107,115,80,...,43,35,47,39,21,37,36,23,36,24
28,Other household theft,1323,1366,1297,1457,1622,1559,1380,1240,981,...,671,588,593,651,581,613,556,656,606,657
29,Theft from a dwelling,154,152,129,96,195,220,174,160,125,...,68,70,68,66,72,53,39,34,44,28
30,Theft from outside a dwelling,1169,1214,1168,1361,1428,1339,1206,1080,857,...,603,518,525,584,509,560,517,622,562,629
31,Vehicle-related theft,1757,2118,2953,3823,4337,4304,3452,2939,2487,...,877,787,918,900,886,726,732,666,747,649
32,Theft from vehicles,1290,1540,2125,2424,2561,2524,2135,1801,1495,...,643,573,652,648,634,499,465,437,478,424
33,Theft of vehicles,286,284,398,516,550,497,372,327,314,...,79,58,82,81,80,98,93,102,100,96
34,Attempts of and from vehicles,180,294,431,883,1227,1283,945,811,679,...,155,156,185,171,173,128,174,127,169,129
35,Bicycle theft,217,288,389,601,578,657,526,395,359,...,326,292,295,315,271,230,203,183,207,185
36,CRIMINAL DAMAGE,2784,2833,2976,2676,3301,3386,3060,2895,2672,...,1210,1169,1083,1145,997,664,664,608,668,587
37,Criminal damage to a vehicle,1592,1720,1638,1669,1781,1847,1667,1601,1511,...,832,797,693,814,675,439,402,373,422,367
38,Arson and other criminal damage,1192,1114,1337,1008,1520,1538,1393,1294,1161,...,378,372,390,331,323,225,263,235,245,220
39,Unweighted base - number of households,9916,11030,10392,10043,14491,16310,14900,19357,32782,...,35248,35334,34636,34103,33655,30822,30704,31375,31647,31631
40,ALL CSEW HEADLINE CRIME EXCLUDING FRAUD AND CO...,11303,12128,13647,15564,18835,19786,17168,15247,12771,...,6529,6057,6247,6431,5661,4385,4589,4595,4722,4538
41,Unweighted base - number of people aged 16 and...,9898,11017,10391,10059,14510,16337,14937,19398,32787,...,35324,35420,34715,34163,33734,31183,30847,31532,31799,31791
42,Fraud [note 9][note 10],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],3395,3255,3809,3676,3526,3177,4159,3560,4072
43,Bank and credit account fraud,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],2485,2241,2579,2474,2135,1885,2449,2092,2495
44,Consumer and retail fraud [note 11],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],736,873,1019,914,825,883,1091,963,1074
45,Advance fee fraud,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],77,69,57,60,391,302,381,333,298
46,Other fraud [note 12],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],97,71,154,227,175,106,237,173,205
47,Computer misuse [note 9][note 10],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],1764,1227,966,876,745,1022,692,952,663
48,Computer virus,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],1191,712,444,360,123,139,128,131,127
49,Unauthorised access to personal inform...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],573,516,522,516,622,883,564,821,536
50,Unweighted base - number of people aged 16 and...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],17171,25725,34163,33734,31183,30847,31532,31799,31791
51,ALL CSEW HEADLINE CRIME INCLUDING FRAUD AND CO...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],11216,10729,11207,10213,8656,8787,9445,9235,9273
52,Unweighted base - number of people aged 16 and...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],35420,34715,34163,33734,31183,30847,31532,31799,31791

In [29]:
sheet1.query("offence_group=='VIOLENCE'")

,offence_group,Jan 1981 to Dec 1981,Jan 1983 to Dec 1983,Jan 1987 to Dec 1987,Jan 1991 to Dec 1991,Jan 1993 to Dec 1993,Jan 1995 to Dec 1995,Jan 1997 to Dec 1997,Jan 1999 to Dec 1999,Apr 2001 to Mar 2002,...,Apr 2015 to Mar 2016,Apr 2016 to Mar 2017,Apr 2017 to Mar 2018,Apr 2018 to Mar 2019,Apr 2019 to Mar 2020\n[note 7],Apr 2022 to Mar 2023,Apr 2023 to Mar 2024,Apr 2024 to Mar 2025,Jul 2023 to Jun 2024,Jul 2024 to Jun 2025
0,VIOLENCE,2063,2014,2265,2900,3768,4464,3746,3375,2551,...,1468,1432,1426,1344,1239,998,1125,1103,1125,1134

In [34]:
mapping["VIOLENCE"]

['Violence with injury',
 'Wounding',
 'Assault with minor injury',
 'Violence without injury']

In [35]:
sheet1

,offence_group,Jan 1981 to Dec 1981,Jan 1983 to Dec 1983,Jan 1987 to Dec 1987,Jan 1991 to Dec 1991,Jan 1993 to Dec 1993,Jan 1995 to Dec 1995,Jan 1997 to Dec 1997,Jan 1999 to Dec 1999,Apr 2001 to Mar 2002,...,Apr 2015 to Mar 2016,Apr 2016 to Mar 2017,Apr 2017 to Mar 2018,Apr 2018 to Mar 2019,Apr 2019 to Mar 2020\n[note 7],Apr 2022 to Mar 2023,Apr 2023 to Mar 2024,Apr 2024 to Mar 2025,Jul 2023 to Jun 2024,Jul 2024 to Jun 2025
0,VIOLENCE,2063,2014,2265,2900,3768,4464,3746,3375,2551,...,1468,1432,1426,1344,1239,998,1125,1103,1125,1134
1,Violence with injury,1226,1208,1592,1778,2407,2622,2365,1974,1507,...,631,702,666,714,591,423,533,391,562,392
2,Wounding,544,454,613,791,874,1077,940,728,709,...,331,379,242,332,341,158,253,136,248,155
3,Assault with minor injury,682,806,978,987,1533,1545,1425,1245,798,...,300,323,423,382,250,265,279,255,315,237
4,Violence without injury,838,806,674,1122,1360,1843,1381,1401,1043,...,837,730,760,630,648,575,592,711,563,742
5,ROBBERY,164,145,178,195,254,322,338,394,340,...,153,129,160,192,127,72,113,83,139,65
6,THEFT OFFENCES [note 8],6292,7136,8227,9792,11512,11615,10023,8584,7209,...,3698,3327,3578,3750,3299,2650,2686,2801,2791,2752
7,Theft from the person,434,505,329,451,611,680,613,593,588,...,363,370,425,447,367,247,347,467,363,462
8,Snatch theft from person,86,63,50,85,84,72,81,56,67,...,43,41,60,58,33,31,78,92,78,93
9,Stealth theft from person,258,315,168,264,345,365,358,322,334,...,197,194,175,209,191,112,126,153,133,151
10,Attempted snatch or stealth theft from...,90,127,111,102,182,242,174,215,188,...,123,136,190,180,143,105,143,222,152,218
11,Other theft of personal property,1586,1729,1798,1737,1933,2073,1942,1565,1370,...,764,640,655,739,612,425,446,432,459,423
12,Unweighted base - number of people aged 16 and...,9898,11017,10391,10059,14510,16337,14937,19398,32787,...,35324,35420,34715,34163,33734,31183,30847,31532,31799,31791
13,Domestic burglary,975,1129,1461,1723,2430,2342,2110,1851,1423,...,697,650,691,699,582,409,402,398,409,376
14,With entry,694,723,869,1166,1592,1510,1273,1236,924,...,425,428,432,441,352,211,222,222,224,218
15,With loss,584,623,714,982,1342,1178,1030,964,673,...,297,275,296,301,240,136,127,132,125,131
16,No loss,110,100,155,184,250,332,243,272,251,...,128,153,136,140,113,75,95,90,99,88
17,Attempts,281,405,591,556,838,831,837,615,499,...,272,222,259,258,229,198,180,177,185,158
18,Domestic burglary in a dwelling,752,916,1225,1372,1751,1708,1547,1230,958,...,492,464,506,517,450,303,294,285,291,270
19,With entry,475,532,666,866,1015,973,818,730,539,...,263,276,295,298,241,141,150,132,143,136
20,With loss,374,454,519,714,818,763,627,521,385,...,167,164,188,192,156,88,74,86,76,78
21,No loss,101,79,147,151,197,210,191,209,154,...,96,112,107,106,85,53,76,46,67,59
22,Attempts,277,384,559,506,736,735,730,500,419,...,229,187,212,219,209,162,144,153,148,133
23,Domestic burglary in a non-connected build...,223,213,236,351,679,633,562,621,465,...,206,186,185,182,132,106,108,113,118,106
24,With entry,219,191,203,301,577,537,455,506,385,...,162,152,137,143,111,70,72,90,81,82
25,With loss,210,170,196,268,524,415,404,442,288,...,130,111,108,109,84,47,53,46,50,53
26,No loss,9,21,8,33,53,122,52,63,97,...,32,41,29,34,27,22,19,44,31,29
27,Attempts,4,21,32,50,102,96,107,115,80,...,43,35,47,39,21,37,36,23,36,24
28,Other household theft,1323,1366,1297,1457,1622,1559,1380,1240,981,...,671,588,593,651,581,613,556,656,606,657
29,Theft from a dwelling,154,152,129,96,195,220,174,160,125,...,68,70,68,66,72,53,39,34,44,28
30,Theft from outside a dwelling,1169,1214,1168,1361,1428,1339,1206,1080,857,...,603,518,525,584,509,560,517,622,562,629
31,Vehicle-related theft,1757,2118,2953,3823,4337,4304,3452,2939,2487,...,877,787,918,900,886,726,732,666,747,649
32,Theft from vehicles,1290,1540,2125,2424,2561,2524,2135,1801,1495,...,643,573,652,648,634,499,465,437,478,424
33,Theft of vehicles,286,284,398,516,550,497,372,327,314,...,79,58,82,81,80,98,93,102,100,96
34,Attempts of and from vehicles,180,294,431,883,1227,1283,945,811,679,...,155,156,185,171,173,128,174,127,169,129
35,Bicycle theft,217,288,389,601,578,657,526,395,359,...,326,292,295,315,271,230,203,183,207,185
36,CRIMINAL DAMAGE,2784,2833,2976,2676,3301,3386,3060,2895,2672,...,1210,1169,1083,1145,997,664,664,608,668,587
37,Criminal damage to a vehicle,1592,1720,1638,1669,1781,1847,1667,1601,1511,...,832,797,693,814,675,439,402,373,422,367
38,Arson and other criminal damage,1192,1114,1337,1008,1520,1538,1393,1294,1161,...,378,372,390,331,323,225,263,235,245,220
39,Unweighted base - number of households,9916,11030,10392,10043,14491,16310,14900,19357,32782,...,35248,35334,34636,34103,33655,30822,30704,31375,31647,31631
40,ALL CSEW HEADLINE CRIME EXCLUDING FRAUD AND CO...,11303,12128,13647,15564,18835,19786,17168,15247,12771,...,6529,6057,6247,6431,5661,4385,4589,4595,4722,4538
41,Unweighted base - number of people aged 16 and...,9898,11017,10391,10059,14510,16337,14937,19398,32787,...,35324,35420,34715,34163,33734,31183,30847,31532,31799,31791
42,Fraud [note 9][note 10],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],3395,3255,3809,3676,3526,3177,4159,3560,4072
43,Bank and credit account fraud,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],2485,2241,2579,2474,2135,1885,2449,2092,2495
44,Consumer and retail fraud [note 11],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],736,873,1019,914,825,883,1091,963,1074
45,Advance fee fraud,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],77,69,57,60,391,302,381,333,298
46,Other fraud [note 12],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],97,71,154,227,175,106,237,173,205
47,Computer misuse [note 9][note 10],[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],1764,1227,966,876,745,1022,692,952,663
48,Computer virus,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],1191,712,444,360,123,139,128,131,127
49,Unauthorised access to personal inform...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],573,516,522,516,622,883,564,821,536
50,Unweighted base - number of people aged 16 and...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],17171,25725,34163,33734,31183,30847,31532,31799,31791
51,ALL CSEW HEADLINE CRIME INCLUDING FRAUD AND CO...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],11216,10729,11207,10213,8656,8787,9445,9235,9273
52,Unweighted base - number of people aged 16 and...,[x],[x],[x],[x],[x],[x],[x],[x],[x],...,[x],35420,34715,34163,33734,31183,30847,31532,31799,31791

In [33]:
sheet1["offence_group"].isin(mapping["VIOLENCE"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
Name: offence_group, dtype: bool

In [36]:
sheet1["offence_group"].values

array(['VIOLENCE', '    Violence with injury', '        Wounding',
       '        Assault with minor injury', '    Violence without injury',
       'ROBBERY', 'THEFT OFFENCES [note 8]', '    Theft from the person',
       '        Snatch theft from person',
       '        Stealth theft from person',
       '        Attempted snatch or stealth theft from person',
       '    Other theft of personal property ',
       'Unweighted base - number of people aged 16 and over',
       '    Domestic burglary', 'With entry', '            With loss',
       '            No loss', 'Attempts',
       'Domestic burglary in a dwelling', '        With entry',
       '            With loss', '            No loss', '        Attempts',
       '    Domestic burglary in a non-connected building to a dwelling',
       '        With entry', '            With loss',
       '            No loss', '        Attempts',
       '    Other household theft', '        Theft from a dwelling',
       '        Theft from outside a dwelling',
       '    Vehicle-related theft', '        Theft from vehicles',
       '        Theft of vehicles',
       '        Attempts of and from vehicles', '    Bicycle theft',
       'CRIMINAL DAMAGE', '    Criminal damage to a vehicle',
       '    Arson and other criminal damage',
       'Unweighted base - number of households',
       'ALL CSEW HEADLINE CRIME EXCLUDING FRAUD AND COMPUTER MISUSE [note 8]',
       'Unweighted base - number of people aged 16 and over',
       '    Fraud [note 9][note 10]',
       '        Bank and credit account fraud',
       '        Consumer and retail fraud [note 11]',
       '        Advance fee fraud', '        Other fraud [note 12]',
       '    Computer misuse [note 9][note 10]', '        Computer virus',
       '        Unauthorised access to personal information (including hacking) [note 12]',
       'Unweighted base - number of people aged 16 and over',
       'ALL CSEW HEADLINE CRIME INCLUDING FRAUD AND COMPUTER MISUSE [notes 8, 9, 10, 13]',
       'Unweighted base - number of people aged 16 and over'],
      dtype=object)

In [37]:
sheet1["offence_group"] = sheet1["offence_group"].str.strip()

In [38]:
sheet1["offence_group"].values

array(['VIOLENCE', 'Violence with injury', 'Wounding',
       'Assault with minor injury', 'Violence without injury', 'ROBBERY',
       'THEFT OFFENCES [note 8]', 'Theft from the person',
       'Snatch theft from person', 'Stealth theft from person',
       'Attempted snatch or stealth theft from person',
       'Other theft of personal property',
       'Unweighted base - number of people aged 16 and over',
       'Domestic burglary', 'With entry', 'With loss', 'No loss',
       'Attempts', 'Domestic burglary in a dwelling', 'With entry',
       'With loss', 'No loss', 'Attempts',
       'Domestic burglary in a non-connected building to a dwelling',
       'With entry', 'With loss', 'No loss', 'Attempts',
       'Other household theft', 'Theft from a dwelling',
       'Theft from outside a dwelling', 'Vehicle-related theft',
       'Theft from vehicles', 'Theft of vehicles',
       'Attempts of and from vehicles', 'Bicycle theft',
       'CRIMINAL DAMAGE', 'Criminal damage to a vehicle',
       'Arson and other criminal damage',
       'Unweighted base - number of households',
       'ALL CSEW HEADLINE CRIME EXCLUDING FRAUD AND COMPUTER MISUSE [note 8]',
       'Unweighted base - number of people aged 16 and over',
       'Fraud [note 9][note 10]', 'Bank and credit account fraud',
       'Consumer and retail fraud [note 11]', 'Advance fee fraud',
       'Other fraud [note 12]', 'Computer misuse [note 9][note 10]',
       'Computer virus',
       'Unauthorised access to personal information (including hacking) [note 12]',
       'Unweighted base - number of people aged 16 and over',
       'ALL CSEW HEADLINE CRIME INCLUDING FRAUD AND COMPUTER MISUSE [notes 8, 9, 10, 13]',
       'Unweighted base - number of people aged 16 and over'],
      dtype=object)

In [40]:
exp = sheet1["offence_group"].isin(mapping["VIOLENCE"])
sheet1[exp]

,offence_group,Jan 1981 to Dec 1981,Jan 1983 to Dec 1983,Jan 1987 to Dec 1987,Jan 1991 to Dec 1991,Jan 1993 to Dec 1993,Jan 1995 to Dec 1995,Jan 1997 to Dec 1997,Jan 1999 to Dec 1999,Apr 2001 to Mar 2002,...,Apr 2015 to Mar 2016,Apr 2016 to Mar 2017,Apr 2017 to Mar 2018,Apr 2018 to Mar 2019,Apr 2019 to Mar 2020\n[note 7],Apr 2022 to Mar 2023,Apr 2023 to Mar 2024,Apr 2024 to Mar 2025,Jul 2023 to Jun 2024,Jul 2024 to Jun 2025
1,Violence with injury,1226,1208,1592,1778,2407,2622,2365,1974,1507,...,631,702,666,714,591,423,533,391,562,392
2,Wounding,544,454,613,791,874,1077,940,728,709,...,331,379,242,332,341,158,253,136,248,155
3,Assault with minor injury,682,806,978,987,1533,1545,1425,1245,798,...,300,323,423,382,250,265,279,255,315,237
4,Violence without injury,838,806,674,1122,1360,1843,1381,1401,1043,...,837,730,760,630,648,575,592,711,563,742